# Generated by Django 4.2.3 on 2023-07-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='year',
        ),
    ]
