# Generated by Django 4.2.3 on 2023-07-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_music_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='music',
            new_name='mus',
        ),
    ]
