# Generated by Django 4.2.3 on 2023-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_music_mus'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='mus',
        ),
    ]
